### PR TITLE
Travis matrix

### PR DESCRIPTION
**Pull request by samhamilton**

### CODE REVIEW

**Comment by samhamilton** [comment]
@pvdvreede bump

**Comment by pvdvreede** [comment]
Hi @samhamilton. Thanks for the PR! Apologies for the late reply.

Could you please provide some context on your changes? I had actually planned to only support 3 versions of Elixir at any point, so now 1.7 is out just support 1.5, 1.6, 1.7 and the requisite Erlang versions for that....

**Comment by pvdvreede** [comment]
Hi @samhamilton I have updated the matrix to test against 1.6 to 1.8, and also published a new version as well so I will close this PR and you can get the latest version.

Many thanks for helping out with the PR! 👍

**Comment by samhamilton** [comment]
@pvdvreede thanks! sorry this got lost in the shuffle - thanks for finishing it off.

**Pull request closed without merging**
